import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Welcome from "@/components/Welcome";
import User from "@/components/User";
import Description from "@/components/Description";
import Pet from "@/components/Pet";

export default function Home() {
  return (
    // Fragment - Envolve as tags que contem o conteúdo do site
    <>
      <Head>
        <title>Fundamento do React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello World! Meu primeiro site em React!</h1>
        <Welcome />
        <User />
        {/* Passando props para os componentes */}
        <Description city="Registro" age={22} email="vinicius@email.com" />
        {/* Componente com desestruturação de props */}
        <Pet name="Pandora" breed="Vira-lata" age={8} />
      </main>
    </>
  );
}
